/* Echo Craft cart prototype. Payment is intentionally disabled until Square integration. */
(()=>{'use strict';const KEY='ec-cart-items-v1',money=n=>'$'+n.toFixed(2),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;'}[c]));let items=[];try{let x=JSON.parse(localStorage.getItem(KEY)||'[]');if(Array.isArray(x))items=x.filter(v=>v&&typeof v.title==='string'&&['single','album','merch','video','bundle'].includes(v.type)&&Number.isFinite(v.price)&&v.price>=0&&Number.isInteger(v.qty)&&v.qty>0).slice(0,100)}catch{}
function save(){try{localStorage.setItem(KEY,JSON.stringify(items))}catch{}}function render(){const checkout=document.querySelector('.ec-cart-checkout');if(checkout)checkout.disabled=items.length===0;const n=items.reduce((a,x)=>a+x.qty,0),counter=document.querySelector('.ec-cart-count'),count=document.querySelector('.ec-cart-quantity'),list=document.querySelector('.ec-cart-list'),total=document.querySelector('.ec-cart-total span:last-child');if(!counter||!count||!list||!total)return;counter.textContent=n;count.textContent=n+' ITEM'+(n===1?'':'S');total.textContent=money(items.reduce((a,x)=>a+x.price*x.qty,0));list.innerHTML=items.map((x,i)=>'<div class="ec-cart-item"><img src="'+escape(x.cover)+'" alt="" loading="lazy"><div><strong>'+escape(x.title)+'</strong><small>'+escape(({single:'Digital single',album:'Digital album',merch:'Merchandise',video:'Digital video',bundle:'Bundle'})[x.type])+'</small><div class="ec-cart-qty"><button data-act="minus" data-i="'+i+'" aria-label="Reduce quantity">−</button><span>'+x.qty+'</span><button data-act="plus" data-i="'+i+'" aria-label="Increase quantity">+</button></div></div><div><span class="ec-cart-price">'+money(x.price*x.qty)+'</span><br><button class="ec-cart-remove" data-act="remove" data-i="'+i+'" aria-label="Remove '+escape(x.title)+'">×</button></div></div>').join('')||'<div class="ec-cart-empty">Your cart is empty.<br>Add music from the catalog to begin.</div>'}
function show(){document.body.classList.add('ec-cart-open');document.querySelector('.ec-cart-close')?.focus()}function hide(){document.body.classList.remove('ec-cart-open')}
function add(data){if(!data||!String(data.title||'').trim()||!['single','album'].includes(data.type))return;const title=String(data.title).trim(),type=data.type,base=Number(data.price),sale=Number(data.salePrice),regular=Number.isFinite(base)&&base>=0.5&&base<=1000?base:(type==='album'?9.99:0.99),price=data.saleEnabled===true&&Number.isFinite(sale)&&sale>=0.5&&sale<regular?sale:regular,id=type+':'+title.toLowerCase(),item=items.find(x=>x.id===id);if(item){item.qty=Math.min(25,item.qty+1);item.price=price;}else items.push({id,title,type,price,cover:String(data.cover||''),qty:1});save();render();show()}
function init(){if(document.querySelector('.ec-cart-launch'))return;document.body.insertAdjacentHTML('beforeend','<button class="ec-cart-launch" type="button" aria-label="Open shopping cart"><svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M6 12h9l9 29h28l7-22H19"/><circle cx="29" cy="51" r="3" fill="currentColor"/><circle cx="49" cy="51" r="3" fill="currentColor"/></svg><span class="ec-cart-count">0</span></button><div class="ec-cart-overlay"></div><aside class="ec-cart-panel" role="dialog" aria-modal="true" aria-label="Shopping cart"><div class="ec-cart-panel-head"><div><h2>YOUR CART</h2><small class="ec-cart-quantity">0 ITEMS</small></div><button class="ec-cart-close" type="button" aria-label="Close cart">×</button></div><div class="ec-cart-list"></div><div class="ec-cart-summary"><div class="ec-cart-total"><span>Subtotal</span><span>$0.00</span></div><p>Pricing is provisional. Digital downloads will be delivered securely. Future physical merchandise may require shipping.</p><button type="button" class="ec-cart-checkout" disabled>Square Sandbox Checkout · Test Only</button><p class="ec-cart-feedback" role="status" aria-live="polite"></p></div></aside>');const checkout=document.querySelector('.ec-cart-checkout');
checkout.disabled=false;checkout.style.opacity='1';checkout.style.cursor='pointer';
checkout.addEventListener('click',async()=>{
  if(!items.length)return;
  checkout.disabled=true;checkout.textContent='Connecting to Square Sandbox…';
  const feedback=document.querySelector('.ec-cart-feedback');feedback.textContent='';
  try{
    const response=await fetch('https://echocraft-music-admin.echocraft-aimusic.workers.dev/api/checkout/sandbox',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:items.map(x=>({title:x.title,type:x.type,qty:x.qty}))})});
    const data=await response.json();
    if(!response.ok)throw new Error(data.error||'Square checkout is not ready.');
    const url=new URL(data.checkoutUrl);
    if(!['square.link','checkout.square.site'].includes(url.hostname)||url.protocol!=='https:')throw new Error('Unexpected Square checkout destination.');
    window.location.assign(url.href);
  }catch(error){feedback.textContent=error.message||'Unable to start checkout.';}
  finally{checkout.disabled=false;checkout.textContent='Square Sandbox Checkout · Test Only';}
});
document.querySelector('.ec-cart-launch').onclick=show;document.querySelector('.ec-cart-close').onclick=hide;document.querySelector('.ec-cart-overlay').onclick=hide;document.querySelector('.ec-cart-list').addEventListener('click',e=>{const b=e.target.closest('button[data-act]');if(!b)return;const i=Number(b.dataset.i),item=items[i];if(!item)return;switch(b.dataset.act){case 'remove':items.splice(i,1);break;case 'plus':item.qty=Math.min(25,item.qty+1);break;case 'minus':if(--item.qty<=0)items.splice(i,1);break}save();render()});document.addEventListener('keydown',e=>{if(e.key==='Escape')hide()});render()}window.EchoCraftCart={add,show};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init()})();